### PR TITLE
Rinbuffer template class

### PR DESCRIPTION
**Pull request by giopde1ste**

### CODE REVIEW

**Comment by giopde1ste** [comment]
>/home/runner/work/Manikin_Software_Libraries/Manikin_Software_Libraries/modules/ringbuffer/test/../src/ringbuffer.hpp:106:36: error: ‘fill’ is not a member of ‘std’

std::fill() has been in the standard library since [C++17](https://en.cppreference.com/w/cpp/algorithm/fill) which version are we using to compile this @Hoog-V ?


>modules/ringbuffer/test/ringbuffer_test.cc:28:  Include the directory when naming header files  [build/include_subdir] [4]

Also I think the linter is not configured correctly, I'm pretty sure we talked about not doing this.

**Review by Hoog-V — APPROVED** [review]
Fixed the workflow... Code looks good. Regarding the cpp version. Normally pio compiles using c++11 standard. You can set it by adding these two lines to platformio.ini

`build_unflags = -std=gnu++11
build_flags = -std=c++17`

**Comment by giopde1ste** [comment]
Aah so that's why. Well we have no need for it now, It doesn't use std::fill anyway now

**Comment by Hoog-V** [comment]
You may merge it when your ready :)

**Pull request merged**
