### PR TITLE
Topic motor and PWM signal

### PR DESCRIPTION
**Pull request by giopde1ste**
This pull request adds the following:

- A motor class to control a connected motor to the samd21
- A suite of pwm classes to create a pwm signal bases on the GCLKx and the TCx/TCCx

Test are not written for both of the new libraries. The pwm classes don't use a lookup table and are therefore only able to make a pwm signal on the samd21 unless modified

### CODE REVIEW

**Comment by Hoog-V** [comment]
This will probably work on the SAMD21 however on SAMD51 it won't even build. I would suggest adding macro's to exclude classes which use SAMD21 specific registers  from building on SAMD51 target. Otherwise it will break the build of the mainboard samd51.

**Review by Hoog-V — CHANGES_REQUESTED** [review]
Unless you use another method of excluding this from the SAMD51 build. I will request you to make some changes to prevent it from breaking the SAMD51 build.

I am gonna test this next week using a sensor hub and oscilloscope

**Comment by giopde1ste** [comment]
I changed it so it now has the guards on the pwm and motor class, I had to do it with the motor class too since is otherwise can't see the used pwm class. For future reference the pwm class can be modified to use other boards by using a lookup table and/or be slightly modified so it can change which registers it uses. Something for the next project group to do.

**Review by Hoog-V — APPROVED** [review]
Good work!

**Pull request merged**
