### PR TITLE
hal I2C base classes

### PR DESCRIPTION
**Pull request by giopde1ste**

### CODE REVIEW

**Comment by Hoog-V** [comment]
CMakefiles need to be updated to use the new i2c module filenames, especially the tests cmakefiles. You need to pull this branch to get the new cpplint workflow. I made the cpplint more tolerable, by removing the build/include_subdir check. The rest of the points pointed out by cpplint are to my opinion quite relevant. Like whitespaces and line length. If you're still not sure about those points, i am open for discussion :)

**Comment by giopde1ste** [comment]
> Like whitespaces and line length. If you're still not sure about those points, i am open for discussion :)

Awesome, I did find out how to setup my auto formatter so the linter is happy. But I also figured out that I just don't like the google format that much. mostly because I like to have more than 2 spaces for indentation cause I find it more readable. Thought @Hoog-V ?

**Comment by giopde1ste** [comment]
So... CMake won't compile because the tests for the hal sensors can't find the i2c because its setup to search for the folder /i2c/ and not /hal_i2c/ and I don't thinks its a good idea for me to change stuff that isn't really part of this topic soo. Its ready for review!

**Review by Hoog-V — APPROVED** [review]
It looks fine to me...

**Review by RichardKroesen — APPROVED** [review]
Checked.

**Comment by giopde1ste** [comment]
@RichardKroesen FWI normally if you review something you don't merge it 😉

**Pull request merged**
